name: Deploy Frontend

on:
  push:
    branches:
      - prod

jobs:
  build:
    name: ðŸŽ‰ Deploy Web App
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: âœ… Verify LFS files are real
        run: |
          ls -lh public/assets/videos/*.mp4 || true
          file public/assets/videos/*.mp4 || true

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: ðŸ›  Install dependencies
        run: npm install

      - name: ðŸ§¾ Create .env file
        run: |
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
          echo "REACT_APP_FRONT_URL=${{ secrets.REACT_APP_FRONT_URL }}" >> .env

      - name: ðŸ›  Build the app
        run: CI=false npm run build

      - name: ðŸ“‚ Deploy standalone build
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude="node_modules/" --exclude=".env"
          path: build/*
          remote_path: /home/ubuntu/riseup-frontend
          remote_host: "${{ secrets.SSH_HOST }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: ðŸŽ‰ Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/riseup-frontend
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
